### ISSUE TITLE
Query without "limit"

### ISSUE THREAD

**Issue by develhox** [drydart/flutter_sqlcipher#4]
#### Actions to reproduce the bug
Call the _SQLiteDatabase.query()_ method without a limit clause.
For example: `SQLiteDatabase.openOrCreateDatabase(path).query(table: tableName)`

#### Expected behaviour
The method returns a cursor with all the rows in the table

#### Bugged behaviour
The library produces an incorrect SQL query and throws the following exception:
`java.lang.IllegalArgumentException: invalid LIMIT clauses:null`

#### Suggested fix
I took a look at the code and I found that the issue is at the line 432 of _database.dart_. To fix it the line 
`      'limit': limit.toString(),`
should be replaced with
`      'limit': limit?.toString(),`

**Comment by artob** [comment]
Thanks! I've released 0.4.3 which includes this fix.
